<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\Answer as BaseAnswer;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class Answer
 * @package Contest\Model
 */
class Answer extends BaseAnswer
{
    use ModelEventDispatcherTrait;
}
