<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\AnswerI18n as BaseAnswerI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class AnswerI18n
 * @package Contest\Model
 */
class AnswerI18n extends BaseAnswerI18n
{
    use I18nTimestampableTrait;
}
