<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\Game as BaseGame;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class Game
 * @package Contest\Model
 */
class Game extends BaseGame
{
    use ModelEventDispatcherTrait;
}
