<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\GameI18n as BaseGameI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class GameI18n
 * @package Contest\Model
 */
class GameI18n extends BaseGameI18n
{
    use I18nTimestampableTrait;
}
