<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\Participate as BaseParticipate;

/**
 * Class Participate
 * @package Contest\Model
 */
class Participate extends BaseParticipate
{
}
