<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\Question as BaseQuestion;
use Thelia\Model\Tools\ModelEventDispatcherTrait;

/**
 * Class Question
 * @package Contest\Model
 */
class Question extends BaseQuestion
{
    use ModelEventDispatcherTrait;
}
