<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Model;

use Contest\Model\Base\QuestionI18n as BaseQuestionI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class QuestionI18n
 * @package Contest\Model
 */
class QuestionI18n extends BaseQuestionI18n
{
    use I18nTimestampableTrait;
}
