<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Action;

use Contest\Action\Base\AnswerAction as  BaseAnswerAction;

/**
 * Class AnswerAction
 * @package Contest\Action
 */
class AnswerAction extends BaseAnswerAction
{
}
