<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Action;

use Contest\Action\Base\GameAction as  BaseGameAction;

/**
 * Class GameAction
 * @package Contest\Action
 */
class GameAction extends BaseGameAction
{
}
