<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Action;

use Contest\Action\Base\ParticipateAction as  BaseParticipateAction;

/**
 * Class ParticipateAction
 * @package Contest\Action
 */
class ParticipateAction extends BaseParticipateAction
{
}
