<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Action;

use Contest\Action\Base\QuestionAction as  BaseQuestionAction;

/**
 * Class QuestionAction
 * @package Contest\Action
 */
class QuestionAction extends BaseQuestionAction
{
}
