<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type;

use Contest\Form\Type\Base\AnswerIdType as BaseAnswerIdType;

/**
 * Class Answer
 * @package Contest\Form
 */
class AnswerIdType extends BaseAnswerIdType
{
}
