<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type;

use Contest\Form\Type\Base\GameIdType as BaseGameIdType;

/**
 * Class Game
 * @package Contest\Form
 */
class GameIdType extends BaseGameIdType
{
}
