<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type;

use Contest\Form\Type\Base\ParticipateIdType as BaseParticipateIdType;

/**
 * Class Participate
 * @package Contest\Form
 */
class ParticipateIdType extends BaseParticipateIdType
{
}
