<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type;

use Contest\Form\Type\Base\QuestionIdType as BaseQuestionIdType;

/**
 * Class Question
 * @package Contest\Form
 */
class QuestionIdType extends BaseQuestionIdType
{
}
