<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Module\Base;

/**
 * Class ContestEvents
 * @package Contest\Event\Module\Base
 * @author TheliaStudio
 */
class ContestEvents
{
    const GAME_CREATE = "action.game.create";
    const GAME_UPDATE = "action.game.update";
    const GAME_DELETE = "action.game.delete";
    const GAME_TOGGLE_VISIBILITY = "action.game.toggle_visilibity";
    const QUESTION_CREATE = "action.question.create";
    const QUESTION_UPDATE = "action.question.update";
    const QUESTION_DELETE = "action.question.delete";
    const QUESTION_TOGGLE_VISIBILITY = "action.question.toggle_visilibity";
    const ANSWER_CREATE = "action.answer.create";
    const ANSWER_UPDATE = "action.answer.update";
    const ANSWER_DELETE = "action.answer.delete";
    const ANSWER_TOGGLE_VISIBILITY = "action.answer.toggle_visilibity";
    const PARTICIPATE_CREATE = "action.participate.create";
    const PARTICIPATE_UPDATE = "action.participate.update";
    const PARTICIPATE_DELETE = "action.participate.delete";
}
