<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\AnswerEvent as BaseAnswerEvent;

/**
 * Class AnswerEvent
 * @package Contest\Event
 */
class AnswerEvent extends BaseAnswerEvent
{
}
