<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\AnswerEvents as BaseAnswerEvents;

/**
 * Class AnswerEvents
 * @package Contest\Event
 */
class AnswerEvents extends BaseAnswerEvents
{
}
