<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\GameEvents as BaseGameEvents;

/**
 * Class GameEvents
 * @package Contest\Event
 */
class GameEvents extends BaseGameEvents
{
}
