<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\GameEvent as BaseGameEvent;

/**
 * Class GameEvent
 * @package Contest\Event
 */
class GameEvent extends BaseGameEvent
{
}
