<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\ParticipateEvents as BaseParticipateEvents;

/**
 * Class ParticipateEvents
 * @package Contest\Event
 */
class ParticipateEvents extends BaseParticipateEvents
{
}
