<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\ParticipateEvent as BaseParticipateEvent;

/**
 * Class ParticipateEvent
 * @package Contest\Event
 */
class ParticipateEvent extends BaseParticipateEvent
{
}
