<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\QuestionEvents as BaseQuestionEvents;

/**
 * Class QuestionEvents
 * @package Contest\Event
 */
class QuestionEvents extends BaseQuestionEvents
{
}
