<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event;

use Contest\Event\Base\QuestionEvent as BaseQuestionEvent;

/**
 * Class QuestionEvent
 * @package Contest\Event
 */
class QuestionEvent extends BaseQuestionEvent
{
}
