<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Base;

use Contest\Form\ParticipateCreateForm as ChildParticipateCreateForm;
use Contest\Form\Type\ParticipateIdType;

/**
 * Class ParticipateForm
 * @package Contest\Form
 * @author TheliaStudio
 */
class ParticipateUpdateForm extends ChildParticipateCreateForm
{
    const FORM_NAME = "participate_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", ParticipateIdType::TYPE_NAME)
        ;
    }
}
