<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Loop;

use Contest\Loop\Base\Answer as BaseAnswerLoop;

/**
 * Class Answer
 * @package Contest\Loop
 */
class Answer extends BaseAnswerLoop
{
    /**
     * You may now add your own logic
     */
}
