<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Loop;

use Contest\Loop\Base\Game as BaseGameLoop;

/**
 * Class Game
 * @package Contest\Loop
 */
class Game extends BaseGameLoop
{
    /**
     * You may now add your own logic
     */
}
