<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Loop;

use Contest\Loop\Base\Participate as BaseParticipateLoop;

/**
 * Class Participate
 * @package Contest\Loop
 */
class Participate extends BaseParticipateLoop
{
    /**
     * You may now add your own logic
     */
}
