<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Loop;

use Contest\Loop\Base\Question as BaseQuestionLoop;

/**
 * Class Question
 * @package Contest\Loop
 */
class Question extends BaseQuestionLoop
{
    /**
     * You may now add your own logic
     */
}
