<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\AnswerCreateForm as BaseAnswerCreateForm;

/**
 * Class AnswerCreateForm
 * @package Contest\Form
 */
class AnswerCreateForm extends BaseAnswerCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "correct" => "Correct",
            "title" => "Title",
            "description" => "Description",
            "question_id" => "Question id",
        );
    }
}
