<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\AnswerUpdateForm as BaseAnswerUpdateForm;

/**
 * Class AnswerUpdateForm
 * @package Contest\Form
 */
class AnswerUpdateForm extends BaseAnswerUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "correct" => "correct",
            "title" => "title",
            "description" => "description",
            "question_id" => "question_id",
        );
    }
}
