<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\GameCreateForm as BaseGameCreateForm;

/**
 * Class GameCreateForm
 * @package Contest\Form
 */
class GameCreateForm extends BaseGameCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "title" => "Title",
            "description" => "Description",
        );
    }
}
