<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\GameUpdateForm as BaseGameUpdateForm;

/**
 * Class GameUpdateForm
 * @package Contest\Form
 */
class GameUpdateForm extends BaseGameUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "title" => "title",
            "description" => "description",
        );
    }
}
