<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\ParticipateUpdateForm as BaseParticipateUpdateForm;

/**
 * Class ParticipateUpdateForm
 * @package Contest\Form
 */
class ParticipateUpdateForm extends BaseParticipateUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "email" => "email",
            "win" => "win",
            "game_id" => "game_id",
            "customer_id" => "customer_id",
        );
    }
}
