<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\ParticipateCreateForm as BaseParticipateCreateForm;

/**
 * Class ParticipateCreateForm
 * @package Contest\Form
 */
class ParticipateCreateForm extends BaseParticipateCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "email" => "Email",
            "win" => "Win",
            "game_id" => "Game id",
            "customer_id" => "Customer id",
        );
    }
}
