<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\ParticipateCreateForm as ChildParticipateCreateForm;
use Contest\Form\Type\ParticipateIdType;

/**
 * Class ParticipateForm
 * @package Contest\Form
 * @author TheliaStudio
 */
class ParticipateUpdateForm extends ChildParticipateCreateForm
{
    const FORM_NAME = "participate_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", ParticipateIdType::class)
        ;
    }

    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "email" => "email",
            "win" => "win",
            "game_id" => "game_id",
            "customer_id" => "customer_id",
        );
    }
}
