<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\QuestionUpdateForm as BaseQuestionUpdateForm;

/**
 * Class QuestionUpdateForm
 * @package Contest\Form
 */
class QuestionUpdateForm extends BaseQuestionUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "title" => "title",
            "description" => "description",
            "game_id" => "game_id",
        );
    }
}
