<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\QuestionCreateForm as ChildQuestionCreateForm;
use Contest\Form\Type\QuestionIdType;

/**
 * Class QuestionForm
 * @package Contest\Form
 * @author TheliaStudio
 */
class QuestionUpdateForm extends ChildQuestionCreateForm
{
    const FORM_NAME = "question_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", QuestionIdType::class)
            ->remove("visible")
        ;
    }

    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "title" => "title",
            "description" => "description",
            "game_id" => "game_id",
        );
    }
}
