<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form;

use Contest\Form\Base\QuestionCreateForm as BaseQuestionCreateForm;

/**
 * Class QuestionCreateForm
 * @package Contest\Form
 */
class QuestionCreateForm extends BaseQuestionCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "title" => "Title",
            "description" => "Description",
            "game_id" => "Game id",
        );
    }
}
