<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Module;

use Contest\Event\Module\Base\ContestEvents as BaseContestEvents;

/**
 * Class ContestEvents
 * @package Contest\Event\Module
 * @author TheliaStudio
 */
class ContestEvents extends BaseContestEvents
{
}
