<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Base;

use Thelia\Core\Event\ActionEvent;
use Contest\Model\Answer;

/**
* Class AnswerEvent
* @package Contest\Event\Base
* @author TheliaStudio
*/
class AnswerEvent extends ActionEvent
{
    protected $id;
    protected $visible;
    protected $correct;
    protected $title;
    protected $description;
    protected $questionId;
    protected $answer;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getVisible()
    {
        return $this->visible;
    }

    public function setVisible($visible)
    {
        $this->visible = $visible;

        return $this;
    }

    public function getCorrect()
    {
        return $this->correct;
    }

    public function setCorrect($correct)
    {
        $this->correct = $correct;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function getQuestionId()
    {
        return $this->questionId;
    }

    public function setQuestionId($questionId)
    {
        $this->questionId = $questionId;

        return $this;
    }

    public function getAnswer()
    {
        return $this->answer;
    }

    public function setAnswer(Answer $answer)
    {
        $this->answer = $answer;

        return $this;
    }
}
