<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Base;

use Contest\Event\Module\ContestEvents as ChildContestEvents;

/*
 * Class GameEvents
 * @package Contest\Event\Base
 * @author TheliaStudio
 */
class GameEvents
{
    const CREATE = ChildContestEvents::GAME_CREATE;
    const UPDATE = ChildContestEvents::GAME_UPDATE;
    const DELETE = ChildContestEvents::GAME_DELETE;
    const TOGGLE_VISIBILITY = ChildContestEvents::GAME_TOGGLE_VISIBILITY;
}
