<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Base;

use Thelia\Core\Event\ActionEvent;
use Contest\Model\Participate;

/**
* Class ParticipateEvent
* @package Contest\Event\Base
* @author TheliaStudio
*/
class ParticipateEvent extends ActionEvent
{
    protected $id;
    protected $email;
    protected $win;
    protected $gameId;
    protected $customerId;
    protected $participate;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    public function getWin()
    {
        return $this->win;
    }

    public function setWin($win)
    {
        $this->win = $win;

        return $this;
    }

    public function getGameId()
    {
        return $this->gameId;
    }

    public function setGameId($gameId)
    {
        $this->gameId = $gameId;

        return $this;
    }

    public function getCustomerId()
    {
        return $this->customerId;
    }

    public function setCustomerId($customerId)
    {
        $this->customerId = $customerId;

        return $this;
    }

    public function getParticipate()
    {
        return $this->participate;
    }

    public function setParticipate(Participate $participate)
    {
        $this->participate = $participate;

        return $this;
    }
}
