<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Base;

use Contest\Event\Module\ContestEvents as ChildContestEvents;

/*
 * Class ParticipateEvents
 * @package Contest\Event\Base
 * @author TheliaStudio
 */
class ParticipateEvents
{
    const CREATE = ChildContestEvents::PARTICIPATE_CREATE;
    const UPDATE = ChildContestEvents::PARTICIPATE_UPDATE;
    const DELETE = ChildContestEvents::PARTICIPATE_DELETE;
}
