<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Event\Base;

use Contest\Event\Module\ContestEvents as ChildContestEvents;

/*
 * Class QuestionEvents
 * @package Contest\Event\Base
 * @author TheliaStudio
 */
class QuestionEvents
{
    const CREATE = ChildContestEvents::QUESTION_CREATE;
    const UPDATE = ChildContestEvents::QUESTION_UPDATE;
    const DELETE = ChildContestEvents::QUESTION_DELETE;
    const TOGGLE_VISIBILITY = ChildContestEvents::QUESTION_TOGGLE_VISIBILITY;
}
