<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Contest\Model\GameQuery;

/**
 * Class Game
 * @package Contest\Form\Base
 * @author TheliaStudio
 */
class GameIdType extends AbstractIdType
{
    const TYPE_NAME = "game_id";

    protected function getQuery()
    {
        return new GameQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
