<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Contest\Model\ParticipateQuery;

/**
 * Class Participate
 * @package Contest\Form\Base
 * @author TheliaStudio
 */
class ParticipateIdType extends AbstractIdType
{
    const TYPE_NAME = "participate_id";

    protected function getQuery()
    {
        return new ParticipateQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
