<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Contest\Model\QuestionQuery;

/**
 * Class Question
 * @package Contest\Form\Base
 * @author TheliaStudio
 */
class QuestionIdType extends AbstractIdType
{
    const TYPE_NAME = "question_id";

    protected function getQuery()
    {
        return new QuestionQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
