<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Controller;

use Contest\Controller\Base\AnswerController as BaseAnswerController;

/**
 * Class AnswerController
 * @package Contest\Controller
 */
class AnswerController extends BaseAnswerController
{
}
