<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Controller;

use Contest\Controller\Base\GameController as BaseGameController;

/**
 * Class GameController
 * @package Contest\Controller
 */
class GameController extends BaseGameController
{

}
