<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Controller;

use Contest\Controller\Base\ParticipateController as BaseParticipateController;
use Contest\Model\Participate;
use Contest\Model\ParticipateQuery;

/**
 * Class ParticipateController
 * @package Contest\Controller
 */
class ParticipateController extends BaseParticipateController
{

    /**
     * Generate Winner for a game
     * @param $id
     * @return \Thelia\Core\HttpFoundation\Response
     */
    public function generateWinnerAction($id){
        $participates = ParticipateQuery::create()->filterByWin(true)->filterByGameId($id)->find();
        if($participates){
            $winner_index = rand(0,count($participates)-1);
            /** @var Participate $winner */
            $winner = $participates[$winner_index];
            return $this->render("winner",["participate_id",$winner->getId()]);
        } else {
            return $this->render("games");
        }

    }

}
