<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace Contest\Controller;

use Contest\Controller\Base\ParticipateController as BaseParticipateController;
use Contest\Event\MailEvent;
use Contest\Event\MailEvents;
use Contest\Model\GameQuery;
use Contest\Model\Participate;
use Contest\Model\ParticipateQuery;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Thelia\Core\HttpFoundation\Request;
use Thelia\Core\Template\ParserContext;

/**
 * @Route("/admin/module/Contest/participate", name="contest.participate")
 * Class ParticipateController
 * @package Contest\Controller
 */
class ParticipateController extends BaseParticipateController
{
    /**
     * @Route("", name=".list", methods="GET")
     */
    public function defaultAction()
    {
        return parent::defaultAction();
    }

    /**
     * @Route("", name=".create", methods="POST")
     */
    public function createAction(\Symfony\Contracts\EventDispatcher\EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator)
    {
        return parent::createAction($eventDispatcher, $translator);
    }

    /**
     * @Route("/edit", name=".view", methods="GET")
     */
    public function updateAction(ParserContext $parserContext)
    {
        return parent::updateAction($parserContext);
    }

    /**
     * @Route("/edit", name=".edit", methods="POST")
     */
    public function processUpdateAction(Request $request, \Symfony\Contracts\EventDispatcher\EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator)
    {
        return parent::processUpdateAction($request, $eventDispatcher, $translator);
    }

    /**
     * Generate Winner for a game
     * @param $id
     * @return \Thelia\Core\HttpFoundation\Response
     * @Route("/winner/{id}", name=".winner", methods="GET")
     */
    public function generateWinnerAction($id)
    {
        $participates = ParticipateQuery::create()->filterByWin(true)->filterByGameId($id)->find();
        if ($participates) {
            $winner_index = rand(0, count($participates) - 1);
            /** @var Participate $winner */
            $winner = $participates[$winner_index];

            return $this->render("winner", ["participate_id", $winner->getId()]);
        } else {
            return $this->render("games");
        }

    }

    /**
     * @Route("/winner/mail/{game_id}/{id}", name=".winner.mail", methods="GET")
     */
    public function processMailWinnerAction($game_id, $id, EventDispatcherInterface $dispatcher)
    {
        $game = GameQuery::create()->filterById($game_id)->findOne();
        $participate = ParticipateQuery::create()->filterById($id)->findOne();

        if ($game && $participate) {
            $event = new MailEvent();

            $event->setGame($game);
            $event->setParticipate($participate);
            try {
                $dispatcher->dispatch($event, MailEvents::SEND);
            } catch (\Exception $e) {

            }

            return $this->render("winner", ["participate_id", $id]);
        }

        return $this->render("games");
    }

}
