<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Contest\Controller;

use Contest\Controller\Base\QuestionController as BaseQuestionController;

/**
 * Class QuestionController
 * @package Contest\Controller
 */
class QuestionController extends BaseQuestionController
{
}
